nodeLinker: node-modules

packageExtensions:
  "@dethcrypto/eth-sdk@*":
    dependencies:
      "@ethersproject/providers": "*"
      "typescript": "*"

  "@chainlink/contracts@*":
    dependencies:
      "ethers": "^5.7.0"

  "ts-command-line-args@*":
    dependencies:
      "typescript": "*"

yarnPath: .yarn/releases/yarn-3.6.0.cjs
