/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as charityApplicationSol from "./CharityApplication.sol";
import type * as interfaces from "./interfaces";
import type * as storageSol from "./storage.sol";

export type { charityApplicationSol };

export type { interfaces };

export type { storageSol };
