import "./addMultisigOwner";
import "./changeAdmin";
import "./changeOwner";
import "./createEndowment";
import "./createIndexFund";
import "./registrar";
import "./updateCharityApplicationConfig";
import "./updateRegistrar";
import "./verifyRegistrar";
