import "./deployAPTeamMultiSig";
import "./deployAccountsDiamond";
import "./deployAngelProtocol";
import "./deployCharityApplications";
import "./deployEndowmentMultisig";
import "./deployGasFwd";
// import "./deployGiftcard";
import "./deployHaloImplementation";
import "./deployIndexFund";
import "./deployLocalRegistrar";
import "./deployRegistrar";
import "./deployRouter";
import "./deploySideChain";
import "./integrations";
