name: "CI"

env:
  DOTENV_CONFIG_PATH: "./.env.example"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: "18.x"

      - name: "Install the dependencies"
        uses: "borales/actions-yarn@v4"
        with: 
          cmd: "install"

      - name: "Lint the code"
        uses: "borales/actions-yarn@v4"
        with: 
          cmd: "format"

      - name: "Add lint summary"
        run: |
          echo "## Lint results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: "Compile the contracts and generate the TypeChain bindings"
        uses: "borales/actions-yarn@v4"
        with: 
          cmd: "compile"

      - name: "Test the contracts"
        uses: "borales/actions-yarn@v4"
        with: 
          cmd: "test"

      - name: "Add test summary"
        run: |
          echo "## Test results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

